name: Docker Compose CI/CD to Elastic Beanstalk

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Build with Docker Compose
      run: docker-compose -f docker-compose.yaml build

    # - name: Run tests
    #   run: |
    #     # Run your test commands here
    #     docker-compose -f docker-compose.yaml up -d
    #     docker-compose -f docker-compose.yaml exec -T your_service_name ./run_tests.sh
    #     docker-compose down

    # The following steps will only execute if the push is to the main branch
    # and all the previous steps have been successful
    - name: Generate deployment package
      if: github.ref == 'refs/heads/main' && success()
      run: zip -r deploy.zip Dockerrun.aws.json .ebextensions

    - name: Upload deployment package to S3
      if: github.ref == 'refs/heads/main' && success()
      uses: actions/upload-artifact@v2
      with:
        name: deployment-package
        path: deploy.zip

    - name: Deploy to Elastic Beanstalk
      if: github.ref == 'refs/heads/main' && success()
      uses: einaregilsson/beanstalk-deploy@v18
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        region: us-west-2
        application_name: tester-rand
        environment_name: Tester-rand-env
        version_label: ${{ github.run_number }}-${{ github.sha }}
        bucket_name: rando-bucket-test-me-today
        bucket_key: deploy.zip
